### ISSUE TITLE
[3] USER STORY: Create articles as editor

### ISSUE THREAD

**Issue by MrMarlonM** [MrMarlonM/good-world-news#10]
#30 
As a **editor** I can **create new articles** so that **I can update the endless feed with the latest news**

### Acceptance Criteria
- It is possible to provide a styled text
- It is possible to add a picture
- It is possible to add a short description

### Tasks

- [x] Create editor group in admin panel and add permissions
- [x] Create first editor user
- [x] Install summernote 
- [x] add summenote to admin panel
- [x] Install cloudinary
- [x] Connect to API
- [x] Wire up cloudinary and change models
