### ISSUE TITLE
[5] USER STORY: about page

### ISSUE THREAD

**Issue by MrMarlonM** [MrMarlonM/good-world-news#20]
#32 
As a **visitor** I can **visit the about page** so that **I learn more about the company and the team**

### Acceptance Criteria
- An about page is existent
- Information about the company and the team is found there
- The information is visible for everyone

### Tasks
- [x] Create About Page Template (HTML)
- [x] Style About Page (CSS)
- [x] Create About View (Django)
- [x] Add URL Pattern
- [x] Link to About Page
- [x] Content Creation
