### ISSUE TITLE
[5] USER STORY: Mobile-friendly navigation

### ISSUE THREAD

**Issue by MrMarlonM** [MrMarlonM/good-world-news#22]
#36 
As a **mobile user** I can **navigate the website easily** so that **everything is accessible**

### Acceptance Criteria
- The navigation bar is toggleable  so that it doesn't use to much real estate
- The nav bar is easily findable at the top of the screen at all times
- Buttons and links are clearly stated as such and distinct from other content
- Buttons are big enough to be pressed on a touch screen

### Tasks
- [x] Create base.html
- [x] Add bootstrap 5
- [x] Add toggable nav bar
- [x] Wire up javascript functionality
- [x] Add custom CSS styles
- [x] All links are added and work as intended
