### ISSUE TITLE
[3] USER STORY: User-friendly design

### ISSUE THREAD

**Issue by MrMarlonM** [MrMarlonM/good-world-news#23]
#36 
As a **mobile user** I can **clearly see the content on the web page** so that **I can enjoy the experience**

### Acceptance Criteria
- The design is responsive to different screen sizes
- On every size the font is clearly readable
- Images adjust their size accordingly
- The elements position themselves according to the screen size

### Tasks
- [x] Add template for newsfeed
- [x] Add template for individual articles
- [x] Add custom CSS
