### ISSUE TITLE
[7] USER STORY: News feed on homepage

### ISSUE THREAD

**Issue by MrMarlonM** [MrMarlonM/good-world-news#24]
#33 
As a **visitor** I can **see the latest news on the homepage** so that **I can directly dive into it without further disruption**

### Acceptance Criteria
- All articles are listed on the homepage
- The articles are listed by date as default
- The title, short description and image can be seen
- When clicked on, the articles opens in full

### Tasks
- [x] Create Models
- [x] Create View
- [x] Create base template
- [x] Create news feed template
- [x] Create article in detail template
- [x] Articles are linked to homepage
