### ISSUE TITLE
[3] USER STORY: Contact form

### ISSUE THREAD

**Issue by MrMarlonM** [MrMarlonM/good-world-news#27]
#34 
As a **visitor** I can **contact the company** so that **I can provide feedback or ask questions**

### Acceptance Criteria
- A feedback form is provided
- The name, mail and message can be put in
- The message is visible to the administrator

### Tasks
- [x] Create new app
- [x] Build model for form
- [x] Create view and url path for it
- [x] Create HTML/CSS code
- [x] Wire everything up
