### ISSUE TITLE
[5] USER STORY: Commenting on articles

### ISSUE THREAD

**Issue by MrMarlonM** [MrMarlonM/good-world-news#3]
#35 
As a **registered user** I can **comment on posts** so that **I can share my thoughts and interact with other users and the authors**

### Acceptance Criteria
- When logged in a comment form is provided
- Every article can be commented by every user
- A confirmation that the comment was submitted or that there was an error is provided

### Tasks
- [x] Create comment model
- [x] Add comment function to view
- [x] Add message to message to comment function
