### ISSUE TITLE
USER STORY: Breaking news for editor

### ISSUE THREAD

**Issue by MrMarlonM** [MrMarlonM/good-world-news#38]
#37 
As a **editor** I can **add an article as breaking news** so that **I can inform users easily and fast about important news**

### Acceptance Criteria
- Through a checkbox I can easily add or unadd articles as breaking news
- The article shows prominently at the top of the page

### Tasks
- [x] Adjust Article model to allow for checking article as breaking news
- [x] Add HTML for breaking news to top of the index.html page 
- [x] Add custom style to breaking news
