### ISSUE TITLE
[2] USER STORY: Like articles

### ISSUE THREAD

**Issue by MrMarlonM** [MrMarlonM/good-world-news#4]
#35 
As a **registered user** I can **like articles** so that **I show that I show my appreciation of it**

### Acceptance Criteria
- Logged in users can like articles
- Every user can like each article only once
- The likes for each article are counted and visible for everybody

### Tasks
- [x] Create Like model
- [x] create like view
- [x] register url path for like functionality
- [x] add like button to index.html and article_detail.html
